author: Uzm Studio Inc.
name: ${project.artifactId}
version: ${project.version}
api-version: 1.8.8

main: ${main-bukkit}
commands:
  tp:
  tpall:
  gamemode:
    aliases: [gm]
  fly:
    aliases: [voar]
  speed:
  group:
  skin:
